### ISSUE TITLE
Subtrajectories issue

### ISSUE THREAD

**Issue by smlee99** [openpathsampling/openpathsampling#1120]
Hi openpathsampling developers. I'm on the stage of learning path sampling simulations. More specifically, I'm trying to obtain the initial reactive trajectory of alanine dipeptide at air/water interface using fixed-length TPS, as explained on [here](https://github.com/openpathsampling/openpathsampling/blob/master/examples/alanine_dipeptide_tps/AD_tps_1b_trajectory.ipynb). Slight modification is made on the code by changing the set of collective variables from `[psi, phi]` to `[comz, phi]`, where comz is the center of mass of three atoms in alanine dipeptide:

```
def compute_comz(snapshot, listRES, listRESmass):
    totPEPmass = listRESmass[0]+listRESmass[1]+listRESmass[2]
    comPEP = listRESmass[0]*snapshot.xyz[listRES[0]][2] + listRESmass[1]*snapshot.xyz[listRES[1]][2] + listRESmass[2]*snapshot.xyz[listRES[2]][2]
    return (comPEP/totPEPmass)

# define the CVs
comz = paths.CoordinateFunctionCV("comz", compute_comz, listRES=listRES, listRESmass=listRESmass)
phi = paths.MDTrajFunctionCV("phi", md.compute_dihedrals, topology=template.topology, indices=[listPHI]).with_diskcache()

# define the states
deg = 180.0/np.pi
beta = (paths.PeriodicCVDefinedVolume(phi, lambda_min=-180/deg, lambda_max=0/deg, period_min=-np.pi, period_max=np.pi) & paths.CVDefinedVolume(comz, -0.2, 5.0)).named("beta")
alpha_L = (paths.PeriodicCVDefinedVolume(phi, lambda_min=0/deg, lambda_max=180/deg, period_min=-np.pi, period_max=np.pi) & paths.CVDefinedVolume(comz, -0.2, 5.0)).named("alpha_L")
```

And it looks like the below part of the code works well:
```
visit_all = paths.VisitAllStatesEnsemble([beta, alpha_L])
trajectory = hi_T_engine.generate(hi_T_engine.current_snapshot, [visit_all.can_append])
```
![image](https://user-images.githubusercontent.com/54790642/190218061-db5e6f27-ecdf-4dbe-bb33-958f00de863c.png)
The above figure, plotted via `plt.plot(phi(trajectory), comz(trajectory), 'k.')` clearly points out that the transition is occurred at phi=0 (here, x-axis), which is the boundary of two states alpha_L and beta. But when I perform the following code:
```
tmp_network = paths.TPSNetwork.from_states_all_to_all([beta, alpha_L])
# take the subtrajectory matching the ensemble (only one ensemble, only one subtraj)
subtrajectories = []
for ens in tmp_network.analysis_ensembles:
    subtrajectories += ens.split(trajectory)
print(subtrajectories)
```

I cannot find any single subtrajectory even though initial reactive trajectory using high temperature integrator was properly made (I guess so?). Since such subtrajectories will be used as initial conditions for further simulations, I need to handle such issue but have no idea why such situation happened. Is this related to the change of defining collective variables? For instance, is it okay to define the state combined with the `PeriodicCVDefinedVolume` and the `CVDefinedVolume`?

**Comment by smlee99** [comment]
![test](https://user-images.githubusercontent.com/54790642/190330650-ab179631-f429-4a91-a295-72737a2d4f0a.png)
I have found that subtrajectory is properly made (as above) when I define the CV as belows:
```
beta = (paths.PeriodicCVDefinedVolume(phi, lambda_min=-180/deg, lambda_max=-10/deg, period_min=-np.pi, period_max=np.pi)).named("beta")
alpha_L = (paths.PeriodicCVDefinedVolume(phi, lambda_min=10/deg, lambda_max=180/deg, period_min=-np.pi, period_max=np.pi)).named("alpha_L")
```

The change is that beta and alpha_L state is not touched with each other at phi=0 (separated by 10deg). Is it necessary to separate the state like such way?

**Comment by dwhswenson** [comment]
Hi @smlee99! Thanks for the question. I had been drafting a reply to your original issue. In response to your updated comment, the answer is basically "yes." Here's the longer response:

It looks like there's no space between your stable states. This is probably not what you want. Specifically, the `phi` variable in your `beta` and `alpha_L` completely cover the space in that variable (and the range of `comz` is the same in both states).

In path sampling, we're trying to enhance sampling of the barrier region. We do this by defining stable states such that there is an area between them that is neither one state nor the other. Typically we aim to have something like 10-100 frames between leaving one state and entering the other (possibly more, depending on your system.)

The idea is that we want to sample frames in the boundary region, in order to characterize the mechanism. And if you don't have a boundary region, this is hard to define. It's literally impossible with flexible-length TPS. Fixed-length might work, but won't give you good results: your states should be where the probably of entering that state from just outside of it is almost 100%. If you don't have a boundary region, and if the divider between your states is at the transition state, then that probability will be near 50%.

A little more explanation on the alanine dipeptide example: we start by creating a path in the flexible length ensemble (in most cases, you probably want to use flexible length path sampling -- it is a more efficient use of computer time.) In that example, we extend the flexible-length trajectory on each side so that the actual transition is near the middle of the long trajectory.

As an aside, are you trying to study a mechanism under constraint? That is, are you looking at something like understanding the mechanism of a conformational change in alanine dipeptide under the constraint that it is near the air-water interface? There are other issues that might come up because of this.

**Comment by smlee99** [comment]
Thanks for your detailed explanation! Is the constraint you mean something like constraining bond lengths or angles involved with a hydrogen atom? I once saw the issue on #1028 . In my simulation I used the HBonds (The lengths of all bonds that involve a hydrogen atom are constrained.) constraint but I can remove such constraint since my system is small (single peptide with 2000 water molecules). Is this also related to the water molecules when they are treated as a rigid body? If it is so, then I may have to care about it.

**Comment by dwhswenson** [comment]
Sorry, I meant more of a "restraint" than full-on "constraint." I wanted to make sure that you understood that OPS doesn't, by default, do anything to restrict your dynamics such that your peptide stays near the air-water interface. From #1121, it sounds like you're planning to use TPS+U to enhance your sampling of trajectories at the air-water interface, which is a perfectly good way to do that. I'll answer more over there, though possibly not until later this weekend. (Short version: yes, I think there's a way to do that, and you're on the right track. Right now it's a little hacky (weird to put all the acceptance probability into the shooting point selector), but I think it'll give you correct statistics. Creating a more elegant way to handle things like TPS+U is definitely something that's already on our radar.)

**Comment by smlee99** [comment]
Ooh yes. I first thought that biasing the axial position of molecule would definitely harm the accuracy of path sampling in some way but in this case it would be fine. Looking forward to your reply and I'll close this issue :)
