### ISSUE TITLE
Add block averaging to get errors on analysis routines

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#191]
We typically calculate the errors in our histograms by splitting the entire MC simulation into some number of blocks of MC steps (I like to use 20 blocks, but 10 is probably the minimum), doing the analysis for each of the blocks independently, and then taking the standard deviation of those "independent" runs.

This should all be automated in the analysis scripts by setting a parameter `n_blocks`. I'm open to suggestion on whether that parameter should default to 1, 10, or 20.

**Comment by jhprinz** [comment]
This is related to Issue #330 .

**Comment by jchodera** [comment]
This is a terrible way to estimate errors.  Why choose 20 blocks if you have no idea what the real correlation time is?  Why compute the standard deviation instead of the standard errors?

Bootstrap is a simple way to estimate errors on independent data, but needs some care if you are working with correlated data.  Correlated block bootstrap methods are probably most applicable here, where you would
* compute some reasonable estimate of correlation time
* use blocks on the same order as twice this correlation time
* resample entire datasets of the same size as the original dataset by drawing blocks with replacement and subjecting these synthetic datasets to the same analysis scheme

The statistics over the bootstrap replicates can then be used to estimate statistical uncertainties (via the stddev), confidence intervals, etc.  This is also a fairly generic approach that can be used even with very complex analysis procedures, so you could build a generic harness to do this for any analysis scheme.

**Comment by dwhswenson** [comment]
This was resolved by #684. We now have a general way to get uncertainty estimates from anything we can turn into a `pandas.DataFrame`. Block averaging is implemented; other resampling methods (bootstrapping) can easily be added.

Automatically identifying block size (correlation time) would be a distant future thing.
