### ISSUE TITLE
Cut 0.9.0 release?

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#548]
As soon as the renaming PRs make it in, can we cut an 0.9.0 release, counting up with 0.9.x releases until the paper is submitted (1.0.0)? I'd really like to start building test conda builds to make sure there are no issues at this point but don't want to do this for git hashes.

**Comment by dwhswenson** [comment]
I see renamings as the only thing that will break backward compatibility at this point (@jhprinz, do you have anything else coming in that would break compatibility?) As far as I'm concerned, we can start cutting releases at any time. I just don't know how frequently we want to, in the build-up to 1.0. Is twice a week enough? It feels like after each merge or even daily would be a bit intense.

My plans for the week to make the SRTIS bias easy to create (it's already possible to do SRTIS, but the input bias is currently a pain to make), progress on renamings/reorgs, and starting on the custom-path mover example for paper 2.

Oh, one other thing that might change the API a little: I think we should move the factory functions outside of a factory class and into separate functions. @jhprinz and I discussed this a while ago (and I think we agreed to do that). I think that's only relevant for the `VolumeFactory` and `EnsembleFactory` classes.

Most of what's left after that is either simplifying things that are currently complicated, or polishing things up to make it all look like it was written by actual professionals (docstrings, documentation, metadata, etc.)

**Comment by jchodera** [comment]
I think it's fine to increment from 0.9.0 whenever you squash some important bugs or make API changes at this point.

> My plans for the week to make the SRTIS bias easy to create (it's already possible to do SRTIS, but the input bias is currently a pain to make)

Would it be easier just to add a [SAMS-based weight adaptation scheme](http://www.stat.rutgers.edu/home/ztan/Publication/SAMS_redo4.pdf)? The implementation takes [just a few lines](https://github.com/choderalab/perses/blob/master/perses/samplers/samplers.py#L1154-L1160) and I'm happy to tackle it.

**Comment by jhprinz** [comment]
> do you have anything else coming in that would break compatibility?

Just merging the stuff for the alanine example which will add  some convenience functions and add some parameters to the `initial_conditions_from_trajectories`. This is almost ready. I am still cleaning the notebook. But the API should be fine now. I also move some of the code to be part of other classes for better reusability.

I think we have done all of the renaming for now. Means next is rearranging folders.

**Comment by dwhswenson** [comment]
> Would it be easier just to add a SAMS-based weight adaptation scheme? The implementation takes just a few lines and I'm happy to tackle it.

No. That would require a different subclass of `PathSimulator`. It isn't the same as standard path sampling. Feel free to do that, because I think it would be great to have, but I think we still need the simplifications I'm talking about.

Everything I need to do is already in the SRTIS notebook. However, previously it needed user intervention to specify what value of the order parameter was associated with each interface. With additions from recent PRs, I can automate that.

**Comment by dwhswenson** [comment]
> Means next is rearranging folders.

I have local branches starting on that already. Waiting for the AD MSTIS example to merge before going too far (in the meantime, creating READMEs for the various subdirectories of the `examples`)

**Comment by jhprinz** [comment]
It should be almost ready. I keep bumping in this I need to fix that are caused by my cleaning up.

**Comment by jchodera** [comment]
Looks like travis is still failing. Any idea how you can fix that?
Would be great to get the test issues fixed before cutting 0.9.0.

**Comment by dwhswenson** [comment]
> Looks like travis is still failing. Any idea how you can fix that?

Re-run it? (which I just did) We may need to increase the number of steps. The last error I saw was due to never running a minus mover. You can't calculate the rate (flux) without that.

The long-term solution is, as I said in #556, to have a separate data file for analysis. In other words, fully separate the integration test for *running* a simulation from the test of the *analysis*. We'd do this by running a long simulation (10k+ steps), hosting the resulting `.nc` file somewhere, and `curl`ing it down for tests.

The trade-off is in how frequently we need to update that file. As long as we're making changes that affect the file format, we would have to update that file with each such change. If that it frequently, then it is more of a pain than what we're doing now.

Once we hit 1.0, that file should *not* change, and in fact it serves as a check for backward compatibility.

@jhprinz : are we close to being able to do that? I'll need to look through my stuff to see what else might affect file format, but I think most of it is already in.

**Comment by jhprinz** [comment]
> @jhprinz : are we close to being able to do that? I'll need to look through my stuff to see what else might affect file format, but I think most of it is already in.

Yes, I just wrote that in the WHAM discussion. The UUID storage allows you to save a long file without the actual coordinates and still run the analysis completely fine (no showing real trajectories of course)

From my side there will not be any changes to the storage for 1.0 (unless bug appear) so we can go ahead and get these files. I will make some little changes to the way to generate initial samples, but that is independent of creating files.

**Comment by jhprinz** [comment]
Note, that for alanine examples we need to use uuid storage (default) for the toy example storing the full file should be fine.

**Comment by jhprinz** [comment]
A new proposal:

Let's just fix storage for 0.9.0 until 0.9.5 (if necessary) and final 1.0.0. So that we can start fixing all the rest using working test files.

I would merge #521 if David has the time before 0.9.0 otherwise we release it and keep on iterating. If we need to make changes on storage then only two times. It should not be too much.

Let's gather, what we want to fix already.

#### Release 0.9.0

- fix storage
- fix ...

**Comment by dwhswenson** [comment]
I probably won't have a chance to complete review until Sunday. Today is going to be a short day, and tomorrow I'm actually taking a day off.

**Comment by jchodera** [comment]
`0.9.0` package is now online:
https://anaconda.org/omnia/openpathsampling/files

I'm going to delete the `0.0.0` `dev` package since it's out of date.

**Comment by dwhswenson** [comment]
> `0.9.0` package is now online:

Woohoo! Thanks @jchodera!

> I'm going to delete the `0.0.0` `dev` package since it's out of date.

Is there a way for us to properly set up a `dev`-labeled OPS? Won't be much different from the `0.9.x` series while those are being released (so doesn't matter in the near future), but once we release `1.0`, I'll rapidly start working on `1.1-dev`...

**Comment by jchodera** [comment]
Do you _need_ a `dev`-labeled OPS? It's actually super easy to install via `pip`, and if deploying on a new platform, you can always use
```
conda install --yes openpathsampling
conda remove --yes openpathsampling 
pip install git+git://github.com/openpathsampling/openpathsamplin.git@master
```
I want to deprecate the old `packagename-dev` scheme, which was causing too much trouble, but we can set up nightly builds pushed to the `dev` label if you really want. Alternatively, we can figure out how to make your travis builds push just the `linux` builds to `dev` label, but this may be of limited utility.

**Comment by dwhswenson** [comment]
> Do you *need* a `dev`-labeled OPS?

Probably not -- depends on if that's how people prefer to stay on the edge of the code. Personally, my preference (and suggestion) is to install the git repo as editable (`pip install -e`), because if you're really on the bleeding edge, you might want to check out an un-merged branch.
