### ISSUE TITLE
Weird storage situation: Add warning if saving without designated store?

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#554]
When I made the `MSOuterTISInterface` object, I forgot to add a store for it.

What's weird is that it seemed to store just fine. In fact, it even reloaded fine. However, it is filled with equivalent (but different) objects, such that the dictionaries in it, etc, don't work.

Maybe this is a weird effect of UUID?

To see the weirdness, run this after running the MSTIS sequence:

``` python
import openpathsampling as paths

storage = paths.AnalysisStorage("mstis.nc")
network = storage.networks[0]

print "Old outers:", network.ms_outer_objects

outer = network.ms_outer_objects[0]
new_outer = paths.MSOuterTISInterface(outer.interface_sets,
                                      outer.volumes,
                                      outer.lambdas)
print "New outer, built from old:", new_outer

print "\nNow let's save it:"
new_store = paths.Storage("test.nc", "w")
new_store.save(new_outer)
```

My output:

``` pytb
Old outers: [<openpathsampling.high_level.ms_outer_interface.MSOuterTISInterface object at 0x11d143490>]
New outer, built from old: <openpathsampling.high_level.ms_outer_interface.MSOuterTISInterface object at 0x11985fd90>

Now let's save it:
Traceback (most recent call last):
  File "test_weird_store.py", line 18, in <module>
    new_store.save(new_outer)
  File "/Users/dwhs/Dropbox/msm-tis/openpathsampling/netcdfplus/netcdfplus.py", line 632, in save
    obj.__class__.__name__)
RuntimeWarning: Objects of type 'MSOuterTISInterface' cannot be stored!
```

I noticed this because, even though the MSOuter the reloaded version had different interface sets in them (making dictionaries fail). It's really cool that it stored it (but where? I couldn't find the store containing it!), but this is the sort of thing where a warning on that kind of save might prevent some debugging time.

**Comment by jhprinz** [comment]
Hmmm, default is that an object will use all attribute that do not start with `_` and store these in a dict. When reconstructing these will be passed to the constructor the generate the object.

In simple cases this works fine. In the OuterMinus I do not think so. You need to implement / override the `to_dict` and `from_dict` methods. 

It will be store in the store that handle the base class. So if it is an `Ensemble` then it will be stored in `storage.ensembles`.

 I will have a closer look tomorrow.

**Comment by dwhswenson** [comment]
The base class is `netcdfplus.StorableNamedObject`. It's designed to work with the default constructor behavior, so no special `to_dict`/`from_dict` should be needed. But since I forgot to modify `storage.py`, I'm surprised that it actually saved.

My point is that it should not have been storable. It got stored as a part of the network, even when the direct `storage.save()` on it gave the correct error shown above. Look at what the example code does. 

Maybe this might is because it was in a list in the network, and lists can be saved? Again, I have no idea where it got saved.

I'm not sure if this is a bug or a feature.

(I added the proper storage support, and now things work as expected.)

**Comment by jhprinz** [comment]
Ah, I thought it is subclassed from `Ensemble`. If it is only subclassed from `StorableObject` then it can still be saved when being inside a storable object, but you cannot find it in any store by index.

The object can be pickled to JSON, because all the objects inside can be pickled and there is a default `to/from_dict`, so that works. If there is no store for this type then it will be placed inside the object that points to it. 

This also means, when you have two objects point to your outer interface it will be stored twice. This is exactly the same, as if you want to store a list of ints. 

I think if the OuterTISInterface is only created for a specific transition then we can leave it this way. If it really is an Ensemble we should subclass it to store it under `.ensembles`. If that does not make sense we really need a new store which I would like to avoid.  Of course the store could be named `_outers` to hide it.

In any case we need to implement `to_dict` and `from_dict` to properly convert the object to a dict and back. This involves all subparts that are generated and should be reproducible. If you generate a joint ensemble inside an object which you store and reference this joint ensemble in another object, then, a loaded object will not contain the same inner object. A new one will be created.

**Comment by dwhswenson** [comment]
It is not an ensemble. I added the new store already. I don't understand why it needs a `to_dict` or `from_dict` if all it stores internally are the parameters for `__init__`. After adding the stores, it works.

**Comment by dwhswenson** [comment]
It's only a factory for the ensemble. See code: https://github.com/openpathsampling/openpathsampling/blob/master/openpathsampling/high_level/ms_outer_interface.py

**Comment by dwhswenson** [comment]
Main point here: So this is expected behavior? Do we have many situations where this is happening? If not, I think a warning somewhere would help, since this could lead to long and frustrating debug sessions. I figured out the problem quickly because I had added the store for `InterfaceSet` just before, and remembered that I hadn't done the same for `MSOuterTISInterface`. But for a less-frequent contributor, this could be really confusing.

I don't think it will be so uncommon for developers to add new kinds of things to store, so it might be worth making that easier. Some sort of registration procedure maybe? Creating a new store for itself on the first attempt to store? You're already doing something like this with Snapshots, right?

**Comment by jhprinz** [comment]
> So this is expected behavior?

Yes, it is. I will pickle what it can.

> Do we have many situations where this is happening?

No, this is the first time. Before we made separate stores to have access to all objects of a certain type and keep them unique when stored several times

> Creating a new store for itself on the first attempt to store? 

That is not trivial. Because it needs to know how you want to store the object. For snapshots I made this possible using the dimensions, etc... But in general you could only have a store that will use json 
pickling and this require a user to correctly implement `to_dict` and `from_dict`. 

The main point here is, that I think it fails because you did not implement these. 

The decision, if these objects should be referenceable (with a UUID) and hence be referenced from multiple objects but stored only once is in theory up to the user. 

Now you can argue that you want all OPS objects to have that quality and I agree that would indeed be nice. We would use a `.untyped` (whatever name is nice) store that can handle all objects. If you have a special store this one is used first. That would actually be a nice addition (for 0.9.5).

Having special stores some advantages:

1. you can iterate all objects of a certain type
2. loading by reference does not require to look up in all objects
3. you can write faster storage especially for your object

If you want I can work on a solution for this. Should not be to difficult, but it will affect storage.

### Now to a possible real problem

You are storing a factory. That is fine and you will be able to recreate the factory. But if the factory is used in some object to create it, the factory will of course not generate the same objects, meaning calling the factory twice with the same arguments will not give the same object. it gives two objects that are equal. And so `a is b` will fail. If that is no problem we are fine otherwise this could make anaylisis complicated.

**Comment by dwhswenson** [comment]
>> Do we have many situations where this is happening?

> No, this is the first time.

In that case, is there a warning when something is getting saved like this? That might help debugging a little.

> Because it needs to know how you want to store the object. For snapshots I made this possible using the dimensions, etc... But in general you could only have a store that will use json
pickling and this require a user to correctly implement `to_dict` and `from_dict`.

The kinds of objects I'm thinking about are simulation objects (things like movers, move schemes, ensembles, etc), not data objects (like snapshots, etc.). Data objects definitely need custom work in storage. 

But what I think people will frequently make are high-level simulation objects to simplify a specific type of simulation. And yes, the user might need to implement `to_dict` and `from_dict`. But the issue is digging through `storage.py` to find all the cases where you do the same thing every time seems a bit much. Also, it would be nice if user's new objects could be self-contained: i.e., storage needs could be handled all in the same file as the new object.

> The main point here is, that I think it fails because you did not implement these.

No. The problem here was that I did not add lines to `storage.py`.

> Now you can argue that you want all OPS objects to have that quality and I agree that would indeed be nice. We would use a .untyped (whatever name is nice) store that can handle all objects. If you have a special store this one is used first. That would actually be a nice addition (for 0.9.5).

Is is possible for each object type have a `._store_name` attribute? Then when it gets saved, the store is created if it doesn't already exist. Default to `"untyped"` if you want.

As I said, users will want to create custom objects that can be stored. For example, so far I haven't even made analysis objects storable, but each of those might take a custom `store`. Do I need to edit `storage.py` every time I create a new analysis that I want to save with my simulation data?

> Now to a possible real problem

This is not a problem. The correct objects are managed in the `network`'s `to_dict`/`from_dict`. (This factory is given as input to another factory which actually creates everything, and so that factory already needed custom `to_dict` and `from_dict`.) The data stored in this object is simply to make connections that other parts of the code can use.

**Comment by jhprinz** [comment]
> Is is possible for each object type have a ._store_name attribute? Then when it gets saved, the store is created if it doesn't already exist. Default to "untyped" if you want.

Hmmm, interesting. Currently it works the other way. You register a store for a base class and then all  subclasses will be stored in that store. Adding a `_store_name` class attribute would make this much easier and you would not have to specify the store name. The problem is that we explicitly put information about the storage into the OPS objects. 

What about a compromise that could salvage this:

You are right, that a user wants to save his own objects. This should be obvious and he will not want to edit `storage.py`. Obvious, too. Assume that a user wants to save his own objects as JSON then right now he could just run

```py
store = ObjectStore(OwnBaseClass)  # create the store itself
storage.create_store('store_name', store)  # save the store in the storage
store.initialize()  # run the initialization of the store and create its own variables in the storage
storage.update_delegates()  # create a representative in `storage.vars` to access the store variables
storage.simplifier.update_class_list()  # update the JSON Pickler to know about the new storable type
```

which will add the store on the fly, but this is _way too_ complicated. If you just want to do this there should be a convenience function to do these steps. That should work for 99% of the user cases. 

```py
# prepare a storage to hold MSM objects simple
storage.add_class_store('msms', MSM)
# more advanced
storage.add_store('msms', ObjectStore(MSM))

# then you can
storage.msms.save(...)
print len(storage.msm)
```

A case where this could fail is. If you have two stores, which both reference each other. This is why
you need all this steps.
This still requires the `to/from_dict` if the object is special. Otherwise this should work out of the box. A single line that can be run anytime.

The other way that always works (right now I hope) is to use the _tag store_

```py
# save an object
storage.tag['base_msm'] = my_msm_object

# load the object
my_msm_objects = storage.tag['base_msm']
```

This requires giving the object a `name`. In this case you just use JSON pickling which works, if all objects are `storable` objects or native python and can thus be converted to a _dict_ that then will be converted to JSON. This will not store the object only once, but again everytime you store it. There is also no way to access all objects of this type and iterate. 

This concept will also work if you have somewhere a OPS objects stored as JSON. Imagine you have a new storable `MoveScheme` that points to your new bias objects. Then it should be storable, if it can be turned into JSON, but again, it will be stored multiple times, if necessary. Where this fails is, if you want to store without JSON, like in `Trajectory` objects. This will store a list of references to snapshot objects and for these you need to have a real store.

If you agree I will add the two functions and make a little example.

**Comment by dwhswenson** [comment]
Closing this as netcdfplus-specific. In SimStore, the "store" for any object that doesn't have an explicit schema is always the `simulation_objects` table. For new simulation objects, this makes sense. For new data objects, the storage schema should be updated. (Although some refactoring is needed to make that easy.)
