### ISSUE TITLE
Really bad scaling in `in_out` for `SequentialEnsemble` prevents visualization

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#557]
In #539, I mentioned that I couldn't get the repex-shoot-repex move to visualize. The problem, it turns out, isn't a bug so much as an implementation that is incredibly slow for sequences that include multiple ensembles.

Run the following:

```python
import openpathsampling as paths
# FullEnsemble as a placeholder
from openpathsampling.ensemble import FullEnsemble
ensA = FullEnsemble()
ensB = FullEnsemble()

def repex_shoot_repex_sequence(n_repeats):
    sequence = []
    for i in range(n_repeats):
        part_i = [paths.ReplicaExchangeMover(ensA, ensB),
                  paths.OneWayShootingMover(ensA, paths.UniformSelector(), engine=None),
                  paths.OneWayShootingMover(ensB, paths.UniformSelector(), engine=None),
                  paths.ReplicaExchangeMover(ensA, ensB)]
        sequence.extend(part_i)
    return paths.SequentialMover(sequence)

import time

for i in range(4):
    mover = repex_shoot_repex_sequence(i)
    start = time.time()
    inout = mover.in_out
    stop = time.time()
    print i, stop-start
```

I got the following output:

```
0 5.00679016113e-06
1 0.00130391120911
2 9.96101999283
```

It never got to the last output, because I killed it after almost an hour. Memory usage for that little script spiked up to 5GB at points (although it mostly hung out in the 200-400MB range).

(Also, having them be different versions of the same ensemble isn't the problem: I did that to simplify the code above; the original test script created a whole network and used two ensembles from that.)

**Comment by jhprinz** [comment]
Yes, I anticipated that. The problem will be that in your particular case there are really A LOT of different cases and possibilities to act upon different initial conditions. To put it simple, you build a mover that not only has lots of different possibilities but all of these possibilities will affect different number of possible in-out relations. (I did not expect to get bad so quickly). 

I should add that all this problem comes from trying to allow an arbitrary number of samples per ensemble! We usually run this in cases where we have only a single replica per ensemble. If that would be known in advance the problem could be MUCH simplified. 

Currently I am not sure if I can fix this of if it is really just that bad of a complex mover, if you want to enumerate all the possibilities. Anyway, we might just remove this for now and run it without the inspection that I hacked together to fix the issue with a user assuming certain inputs and possibly wondering why the visualization is different.

Any ideas?

**Comment by dwhswenson** [comment]
If you simplify the possible sets after each step, this shouldn't a problem for this case. (It still is a problem in the worst case, but not here.) If I did this by hand, I would say the following: before the first step, I need at least one in `ensA` and `ensB` (repex REQUIRES both). After repex, if I accept, I have at least one in `ensA` and at least one in `ensB`. If I reject, I have at least one in `ensA` and at least one in `ensB`. Simplifying after that, I have `(ensA, ensB)`, not `((ensA, ensB), (ensA, ensB))`. Continue from there; after each step, I have only the pair `(ensA, ensB)`.

Not sure what your code does, but if you treat `SequentialEnsemble` that way, this shouldn't be a problem.

**Comment by jhprinz** [comment]
I think I fould a bug :( Now it should be fast enough...

**Comment by dwhswenson** [comment]
This still doesn't work. See if you can run the commented-out example in cell 18 of https://github.com/openpathsampling/openpathsampling/blob/master/examples/ipython/move_strategies_and_schemes.ipynb. That's the example that needs to run.

**Comment by jhprinz** [comment]
Just checked it and it does work, but the scheme you designed has really a _lot_ of possibilities. What I did is to only evaluate the `in_outs` of a subpart of the long sequential mover you designed. What happens is that in the beginning there are only repex and the number of possibilities is small. Once you couple using the union ensemble it goes up. The using shooting moves it goes up even more. And once the reversed repex start it blows up quickly. From the 18 moves after number 12 there are already over 20k and I did not reach the next level...

The crucial point is that this _only_ happens if you allow more than one sample per ensemble. If there is at most one sample per ensemble than it really is only a single possibility (at least up to step 12). Since this will be the most common case, I will add a way to only evaluate under the assumtion of at most one sample per ensemble. Or limit the maximal number of samples per ensemble.

**Comment by jhprinz** [comment]
Correction. It is strictly one, if you assume that all movers accept. Otherwise there are much more.
I corrected this and added a little more intelligence on the way:

1. A move that does not alter a trajectory only _moves_ it to a different ensemble is treated as such. So an application of two RepExMoves in sequence will counter each other and the only possible results are no changes or a single swap, if one of the two did not accept.

2. Same works for two PathReversals

The issue of working with SRTIS is still not solved and requires a much more general approach. Adding this would probably make it too slow so I leave it this way. A PR to fix this is on the way. Currently still take 40 seconds. I see, if I can make it a little faster though. 

The code inside the plotting is not very efficient. I think a factor of 4 should be possible without much effort

**Comment by dwhswenson** [comment]
> The issue of working with SRTIS is still not solved and requires a much more general approach. 

If this is the case, then what is the advantage of all this extra code (and slower runtimes) over what we had before #500?

**Comment by jhprinz** [comment]
What is the advantage of better treatment of moves?

That in case you construct a mover that does lots of path reversals you see now that there is no mixing, but lots of moves... In this case is increases speed a lot. 

Not so, in the case of your repexshootingrepex.

Another nice thing is so see is between which ensembles there is possible mixing. There is a little function that shows that now.

And, I like it to be correct in this sense as you say, otherwise the user might be confused because if we does two PathReversals in ensemble 1 and wonders why there are certain possibilities. 

The slowness in this case is because there are finally 42000 possibilities, that each include movings between the ensembles. In total 280,000. That includes all possible accept/reject that can happen. And evaluating all of these takes about `30s`. And that is only, if you limit the possibilities to one sample per ensemble. 

Another `10s` are for the visualization to check for all possible outcomes.

**Comment by dwhswenson** [comment]
Okay, but are any of these advantages used in the move scheme visualization? As far as I can tell, we're getting the same visualization as before #500, and taking orders of magnitude longer.

**Comment by jhprinz** [comment]
Well, yes, I just checked. With this two additions it goes from 2.5s to 35s. This is a lot. This is mainly due to the fact, that it knows afterwards exactly if under a ensemble change the trajectory was altered, reversed or just copied. 

I agree, this makes it very slow so I make it optional. Would it be okay, if the time would only be marginally longer?

**Comment by dwhswenson** [comment]
This needs to be interactive. If, on an example like this, it takes more than a few seconds, then it really isn't okay. A minute for a really large move scheme (thousands of movers), maybe. But for these, it should be fast.

If we're getting the same resulting visual as we would have without InOut, then don't use InOut for the visual.

**Comment by jhprinz** [comment]
Okay, I implemented these because of your objections to a user being confused with a very specific detail, where I agree that this might be a problem. The other solution would have been to explain why the visualization would not be able to show this. 

Now, I have a working solution that can do the analysis in most cases very quickly and default is that is works the way intended. It now takes a few seconds even in the RepEx case. 

I have two options that allow to use it for more details in special cases (if you know what you are doing). These are class variables and usually not used, but you can enable treatment of move than a single samples per ensemble and you can enable to check for reversals and copied of trajectories to see, if your scheme might not do what you expect it to. It think that is the best compromise. 

Not sure if we will use this feature a lot, but I think there are cases where this definitely is useful.

For now I would use the additional features (which do not affect speed, if not used) to be experimental. They work, so why not use them.

Does that make sense?

The figure now takes 3.8 seconds. All others are pratically instant.

**Comment by jhprinz** [comment]
<img width="358" alt="mix" src="https://cloud.githubusercontent.com/assets/5091934/17780031/2e96849a-656a-11e6-8bac-d899351564a4.png">

An example for the mixing of ensembles.

Another comment on the problems of using SRTIS. This add another complexity of having an explicit dependence of moves on incoming sample_set structure. So certain moves will only be available at all, when certain ensembles are present. This makes it very hard and costly to track. Possible but I have not time to implement that for now. And don't even ask me about speed ;)

**Comment by dwhswenson** [comment]
> Okay, I implemented these because of your objections to a user being confused with a very specific detail, where I agree that this might be a problem.

Right, but what you're telling me is that you *can't* actually solve the problem I was concerned about (you can't do single replica; the concern was about single replica minus movers). That's why it sounds to me like the InOut has no advantage.

> Not sure if we will use this feature a lot, but I think there are cases where this definitely is useful.

Well, the move scheme visualization should be used any time you make a custom move scheme, just to be sure you're doing what you think. I think that will be common for advanced users. That's why it should also be fast.

I think you're trying to solve a problem that doesn't need to be solved. We don't need to enumerate every path through the DAG, which is effectively what you're doing (actually, you're doing something harder than that -- you're enumerating every path through a much more complicated space than the DAG). 

We just need to know that the input and output ensembles for a mover are.

The problem that started all of this was that an ensemble was marked as required input on a `SequentialEnsemble`, even though it isn't (because a previous step in the `SequentialEnsemble` creates a sample in that ensemble.

isn't this more easily solved by having, in addition to `input_ensembles`, an `optional_input_ensembles`? This would consist of all ensembles that were outputs to previous steps in the sequence and are inputs to later ensembles in the sequence. These are not required inputs to the mover, but if such a sample exists in the sample set, that sample might be used instead of the required.

I think this would solve the original problem. It would also make more sense when visualizing a `RandomAllowedChoiceMover`: for single replica, all ensembles are optional (since you need one of any). But you could make a `RandomAllowedChoice` where all submovers require one of the ensembles, while other ensembles are optional depending on the submover.

> For now I would use the additional features (which do not affect speed, if not used) to be experimental. They work, so why not use them.

As long as they don't slow down the stuff that actually gets used, then fine. But make sure there are tests for the output of these things. I think a lot of them will be replaced by more efficient approaches when we properly wrap our movers in a DAG. It really seems to me like you're trying to reinvent a lot of stuff from graph theory.

> An example for the mixing of ensembles.

This still doesn't visualize the ensemble-set to ensemble-set stuff you're calculating. As such, that level of detail isn't needed.

I think this would be much easier to calculate by making a (multi)graph where ensembles are represented by nodes and movers are edges. You can come up with simplification algorithms for `Sequential`/`RandomChoice`, which would give you a graph that corresponds to the thing you plotted. My guess is that this would scale linearly with the number of entries in the DAG, and therefore be a lot faster.

**Comment by jhprinz** [comment]
> isn't this more easily solved by having, in addition to input_ensembles, an optional_input_ensembles

Well, it needs to handle multiple combinations of possible ensembles. An you need to specify this correctly also each possibility can contain ensembles multiple times. All these possibilities have specific output ensembles for each of these inputs and a mover needs to be able to specify this.

Correct. I added more (because I found it chanllanging to figure that out) for a mover to also know how the replicas from inputs are shifted around because that will in addition allow us to realize that a mover is undoing work it did before, or not doing anything. 

I know that is not what you wanted, but I found it useful and a nice demonstration. This of course is computational much slower than the rest. Although all ways are still complex. 

> making a (multi)graph where ensembles are represented by nodes and movers are edges

Well, ich you consider all possible ensemble combinations with their multiplicity as nodes, then yes. Because picking optional outcomes depending on the input structure is what makes it so hard and difficult. But this is definitely 2.0. A PR is coming.
