### ISSUE TITLE
PathTree Bug(s)

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#622]
When I try to generate a path tree from a TPS simulation with the code:
``` python
tree = ops_vis.PathTree(
    steps[:],
    ops_vis.ReplicaEvolution(replica=0, accepted=True
    )
)
tree.options.css['scale_x']=0.5/len(steps)
tree.options.css['width'] = '200%'
SVG(tree.svg())
```
where ```steps``` is a list of mc steps from multiple save files(the tps simulation is broken across multiple save files). It only shows the step numbers of the last file and an asterisk for all others, as seen in:

![tree](https://cloud.githubusercontent.com/assets/19587267/19854630/402848ac-9f70-11e6-93c5-f968e0f7158f.png)

While running
``` python
step = steps[20]
print step.mccycle
```
gives:
```
20
```
Also, could it be possible to scale the vertical connectors independently?
Because as you can see, above the highlighted try: the width of my trajectories are actually smaller than the connectors. This scaling issue is probably because my original trajectory was taken with a 10x higher save frequency (resulting in 74000 frames in comparison to around 100 for the short tries). It is actually cut off in the above image, this is the full image (without the width scaling):
![full_tree](https://cloud.githubusercontent.com/assets/19587267/19854899/c8ec548e-9f71-11e6-883a-7134dc8f4558.png)

Lastly, the automatic scaling (without both the width and scale_x option), results in an unreadable image (I first thought I got no output at all):
![wrong_tree](https://cloud.githubusercontent.com/assets/19587267/19855560/8986d054-9f75-11e6-9086-2813af98d5f5.png)

**Comment by jhprinz** [comment]
Last things first: About the scaling: Yes, the problem with trees and very different lengths of trajectories is annoying and I thought about a nice solution, but might come later. Quick about the different for `scale_x` and `width`. 

`scale_x` represents the effective pixels between two frames and thus affects the overall size of the figure. 
`width` only affects the output width in the browser. So it does not change the effective number of pixels of the embedded SVG. If you use `'width': 'inherit'` it will use the calculated number of pixels of the SVG also in the browser. `100%` will rescale the figure to fit, etc...

If you use `scale_x` the way you do. Then you rescale the real pixels to be more narrow, while the width of the connecting bars is fixed and actually a `css` property that you can change using Javascript. 

I agree that there should be an easy way to change the `css` of a figure to you liking and I will add that. 

Now the first problem of the step: When you use `ReplicaEvolution` then what happens is, that it starts with the last step you give and get the replica and from there it traces back using the `parent` property of each sample. It does not use the steps! And I think that is indeed the wrong behaviour, although in most cases it will give you the right behaviour. 

In your particular case this may lead to the result you have: Imagine me using only `steps[50:60]` in the `ReplicaEvolution` then it will pick the replica from `step[59]` and trace back beyond step 50 and earlier until there is no `.parent` for a Sample. When this list is generated we try to figure out which sample was actually generated in which step and since you only have steps 50 to 60 to inspect all samples created at earlier steps will not be known and hence the `*` is shown.

Now. You said that you split the simulation but step[20] has step number 20. And this is indeed strange so I need to look into what can happen there. I will get back to you.

A short summary if things to do for me:

1. Easy access to CSS properties
2. Check ReplicaEvolution or create a `StepEvolution` generator to really inspect the change after each step. (I think that maybe `SampleAncestors` and `ReplicaEvolution` got somehow mixed)
3. Look into potential bug of step numbers

**Comment by jhprinz** [comment]
@sroet Quick question: How do you join all the steps from multiple files. Do you do something like this?
```py
steps = []
for file in files:
   st = Storage(file)
   steps.extend(st.steps)
```

Can you do

```
print type(steps)
```

and try

```
tree.steps._create_step_sample_list()
SVG(tree.svg())
```

and see if that changes anything? It seems the list of sample -> step is not updated correctly.

And I forgot this:
> Lastly, the automatic scaling (without both the width and scale_x option), results in an unreadable image (I first thought I got no output at all):

This is strange. Maybe you figure is way to big and the browser fails?

**Comment by sroet** [comment]
@jhprinz 
I run 
``` python
steps = sum([s.steps[:] for s in storages],[])
```
where ```storages``` is generated by:
```python
storages = []
for filename in filenames:
    storages.append(paths.Storage(filename, 'r')
```
When I run:
``` python
print type(steps)
```
it gives:
``` python
<type 'list'>
```
if I run 
``` python
tree.steps._create_step_sample_list()
SVG(tree.svg())
```
After I generated the tree with the code of my first post. It doesn't change anything and gives the same image

If I however make a tree for ```step[:50]``` (my storage is split every 25 steps after the first decorrelation of 2 steps), it now know the step numbers of again the last save file(from 27 to 50)

Also, if I run with ```accepted = False``` it now knows all the step numbers as can be seen in:
![false_tree](https://cloud.githubusercontent.com/assets/19587267/19898785/cd038b22-a05d-11e6-8e85-886fe68a9c97.png)
