### ISSUE TITLE
NetCDF Corrupt : "RuntimeError: NetCDF: HDF error " when storage space runs out.

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#707]
Hello
I cannot load back the storage (NetCDF file) for a simulation using OPS which stopped because the storage space ran out on my machine. The RuntimeError suggest the storage is corrupt. I could be a possible bug. 

Is there a way to checkpoint the storage to safely close it with last MC step etc when such an issue happens ?

**Comment by jhprinz** [comment]
Hi,
Could you post the error message here? The question is, if it is an error in the netCDF or the extension only. In the first case it really means that the file is corrupt and that is a bug that should be fixed, although I am uncertain, if that can be fixed or rolled back.

If it is a problem that the OPS Storage wrapper fails, we can fix that, but I need to know what the error is.

**Comment by arjunwadhawan** [comment]
Following are the errors
1- In the log file while saving the simulation's last step 
2- While loading back the NetCDF file 

[ops_saving_error.zip](https://github.com/openpathsampling/openpathsampling/files/1274212/ops_saving_error.zip)

**Comment by jhprinz** [comment]
This really is a netCDF error and we should ask there, if someone knows what to do. Do you need to recover data in the file? Or do you just want a precaution. We could add a check on free diskspace if that helps.

**Comment by dwhswenson** [comment]
> We could add a check on free diskspace if that helps.

I think this would be a good thing anyway, if it is easy to implement. However, implementation might not be totally trivial. We save a trajectory at a time; that can be 10+ GB of data for a large system. But running a toy model on my laptop I might not even have 10 GB of disk space available (and would be fine without it). So it would somehow need to adjust to the size of the object (and I'd rather do the disk space check once per traj instead of at every snapshot, because I think it'll start to get painfully expensive for toy models otherwise.)

@jhprinz : Is there anything in the caching stuff you've already implemented that would make it easier to estimate the disk required?

Alternative: Does netCDF have any sort of roll-back procedure that we can use over the course of a trajectory? It might be nice to catch this error, roll back to the last reasonable save point, and reraise it as `RuntimeError("NetCDF Error: HDF Error (disk may be full)")`.

**Comment by jhprinz** [comment]
I fear that disk full is bad. I am not sure what happens and also not on how to test it :) We should ask that in the issues of netcdf. The error suggests that it will just crash and exit and then there is no way to roll-back anymore. If OPS fails we can always still load the rest...

**Comment by jhprinz** [comment]
> Is there anything in the caching stuff you've already implemented that would make it easier to estimate the disk required?

Not really. I would say we just forbid saving when the diskspace is less than, say 100MB. Just to be really safe.

**Comment by dwhswenson** [comment]
> The error suggests that it will just crash and exit and then there is no way to roll-back anymore.

There's no way to catch this error and try to recover from it? I get that testing might be non-trivial here, although you could probably make a mock that does the normal storage for a couple saves then throws an error mimicking this.

> I would say we just forbid saving when the diskspace is less than, say 100MB.

When are you talking about doing the check? The problems are:

1. If you check before every object is saved, that will be brutal on performance for toy engines. OPS overhead is already the vast majority of the cost when running toy models; let's not make that worse.

2. If you check before each step/trajectory, 100MB is likely not enough. For moderate-sized systems (20k atoms), a trajectory is often on the order of GB. For larger systems, this can reach 10GB/traj. Checking at 100MB won't prevent the problem.

**Comment by arjunwadhawan** [comment]
> This really is a netCDF error and we should ask there, if someone knows
> what to do. Do you need to recover data in the file? Or do you just want a
> precaution. We could add a check on free diskspace if that helps.
>
i do not wan to recover this file as it was a kind of test run. But as you
discuss, it would be good to have a check of free disk space
-- 
Arjun
PhD Student - Van 't Hoff Institute for Molecular Sciences
University of Amsterdam
7872228509
LinkedIn Profile : https://www.linkedin.com/in/arjunwadhawan

**Comment by dwhswenson** [comment]
Closing this; netcdfplus development has been dropped in favor of SimStore. This shouldn't be a problem in SimStore (or raise an issue if it is). I'm not sure how to test this, but in principle, SimStore (using SQLite backend) should have the following behavior:

1. A disk-full error should crash the code (that's intended -- stop computing if you can't save the results!)
2. You should be able to open that file, because the SQL transaction approach shouldn't leave the DB in a corrupted state.
3. You might not be able to load the last step, since it may have only been partly saved. But other steps should be fine.
