### ISSUE TITLE
ShootingPointAnalysis items() and values() not working/result in error

### ISSUE THREAD

**Issue by hejung** [openpathsampling/openpathsampling#722]
The issue here is that the keys are strings but that \_\_getitem\_\_ expects them to be snapshots and tries to hash them. Since they are already hashed this results in an error, because naturally the strings do not have a coordinate attribute.
I have a fix for this behavior on  https://github.com/hejung/openpathsampling/tree/fix_SPA
I have added a conditional in \_\_getitem\_\_ checking if it is a string (->use key to take the snapshot from hash_representatives and use that as a key) or not (-> take the key as key).
EDIT: this breaks as soon as the keys are not strings anymore. The only general fix I can think of is (re)implementing .items() and .values() instead of inheriting them from Mappable but I am not sure if that is a good idea.

**Comment by dwhswenson** [comment]
This is a good catch. However, I don't think it is essential to fix it before 1.0 (where committor-ish things are secondary), so @hejung, could you make a  PR that we can include as part of 1.1?

**Comment by hejung** [comment]
@dwhswenson yes, I will create a fix, after having thought about it most likely by (re)implementing .values() and .items() and the corresponding iterators, if that is ok with you?

**Comment by dwhswenson** [comment]
It's been a while since I wrote that code, and you, @hejung, have been working with it more than me lately, so let me know if any of this sounds wrong:

Looking back at this, I think the intention was that we should be able to use coordinates as keys, even though (as numpy arrays) they can't be hashed. So I convert them to a string representation, which can be hashed. The idea is that there's an *internal* definition of the key (which is a string), which differs from the *user-facing* key (which is a snapshot, from which we get the coordinates, from which we get the string representation).

In that case, I think it makes complete sense to override `.keys()` and `.items()`. They should probably use what I call the "representative snapshot" (which will be, IIRC, the values of the `hash_representatives` attribute -- in practice, that's the first snapshot with those coordinates.)

(Above you wrote `.values()` and `.items()` -- I assume you meant keys, not values?)

Also, don't worry about the iter variants -- in Python 3, `.keys()`, `.values()`, and `.items()` *are* iterables, and `.iterkeys()` etc no longer exist. I think you can write this such that you get lists in Python 2 and iterators in Python 3, just by calling the right object's `.keys()`/`.values()`. If not, go ahead and make them all iterators -- Python 2 support is on the way out.

**Comment by hejung** [comment]
@dwhswenson 
Sounds very reasonable!
I did not think about the fact that the underlying python objects will do the py2 -> py3 / list -> iterator transition for me.
.values() failes at the moment too because self.keys() gives the hash-strings, but it is probably enough to reimplement .keys() since values() is [self[key] for key in self.keys()].
