### ISSUE TITLE
Bug in HistogramPlotter2D limits

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#730]
When trying to run the following code in jupyter, changing the x-limits doesn't behave as expected. 
```python
%matplotlib inline
import pickle
from openpathsampling.numerics import HistogramPlotter2D
import matplotlib.pyplot as plt

with open('test_pdh.p', 'r') as f:   
    pdh = pickle.load(f)

HistogramPlotter2D(pdh).plot(xlim=(0.0, 2.5),
                             ylim=(0.0, 2.5),
                             vmin=0, vmax=1,
                             cmap='Blues')
plt.show()
plt.close()

HistogramPlotter2D(pdh).plot(xlim=(0.5, 2.5),
                             ylim=(0.0, 2.5),
                             vmin=0, vmax=1,
                             cmap='Blues')
plt.show()
plt.close()
```
returns
![working](https://user-images.githubusercontent.com/19587267/32790248-31c78840-c95e-11e7-8d0c-6e10b77a7446.png)
![not_working](https://user-images.githubusercontent.com/19587267/32790253-36303f1c-c95e-11e7-87e9-3c36d991c68e.png)

where I expected the second one to be scaled from 0.5 to 2.5 but instead runs from 1 to 3?

[test_pdh.zip](https://github.com/openpathsampling/openpathsampling/files/1471527/test_pdh.zip) contains the pickled path density histogram. (without the cv objects as cvs, as those were not happy being pickled, so I changed them to strings). The pdh was build using ```left_bin_edges=[0,0], bin_widths=[0.025, 0.025]```

**Comment by dwhswenson** [comment]
This is definitely odd (note that it even actually *plots* to 2.5, with the rest not being treated by the cmap). My guess is it has something to do with the weird inner workings of `HistogramPlotter2D` (which converts to `pandas.DataFrame` to do the plotting, but then must do some clever stuff to shift between the internally-used integer axes and actual floats you expect).

I'll look at it soon.

**Comment by dwhswenson** [comment]
I have a rough picture of what is going wrong, although I might not get around to fixing it for a few days. In the meantime, here's a workaround. Add `import matplotlib.pyplot as plt` to your imports, then:

```python
plotter = HistogramPlotter2D(pdh)

xlim = (0.5, 2.5)
ylim = (0.0, 2.5)

plotter.plot(xlim=xlim,
             ylim=ylim,
             vmin=0, vmax=1,
             cmap='Blues')

n_bins_x = plotter.to_bins(xlim[1], dof=0) - plotter.to_bins(xlim[0], dof=0)
n_bins_y = plotter.to_bins(ylim[1], dof=1) - plotter.to_bins(ylim[0], dof=1)
plt.xlim(0, n_bins_x)
plt.ylim(0, n_bins_y)
```

This should work no matter what limits you use.

(Details, mostly for myself if I can't get to this quickly: `pandas.DataFrame` indices are always from 0, so when plotting, the bins always go from `0` to `n_bins` ... the ticks and labels were correct, but the range assumed that the bin numbers were also shifted. As a subtlety, I hadn't noticed this in the examples because I thought it was tested when I zoomed in on the AD path density. However, `pandas.DataFrame` labels like a spreadsheet -- 0,0 is the top left, not the bottom left like a scientific plot. So keeping the same top left and changing the bottom and right explicitly did *not* test this. Some tests may have to change, since I think I may have mocked incorrect behavior.)
