### ISSUE TITLE
Can not restore openmmtools integrator

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#767]
After the recent merge of PR #764, I can not load in a previously saved `openmmtools` integrator (VVVR).
running: 
``` python
storage = paths.Storage('storage_name.nc','r')
scheme = storage.schemes[0] 
```
raises the error (relevant part of the traceback):
```
/faststore/homedirs/10166149/github_files/OPS/openpathsampling/openpathsampling/engines/openmm/engine.pyc in from_dict(cls, dct)
    324 
    325         integrator = simtk.openmm.XmlSerializer.deserialize(integrator_xml)
--> 326         integrator = restore_custom_integrator_interface(integrator)
    327         return OpenMMEngine(
    328             topology=topology,

/faststore/homedirs/10166149/github_files/OPS/openpathsampling/openpathsampling/engines/openmm/engine.pyc in restore_custom_integrator_interface(integrator)
     32         RestorableObject = openmmtools.utils.RestorableOpenMMObject
     33         if RestorableObject.is_restorable(integrator):
---> 34             success = RestorableObject.restore_interface(integrator)
     35             logger.debug("Restored interface to integrator: " + str(success))
     36             # this return a bool based on success; we could error on fail,

/home/10166149/miniconda2/lib/python2.7/site-packages/openmmtools/utils.pyc in restore_interface(cls, openmm_object)
    812         except KeyError:
    813             raise RestorableOpenMMObjectError('Could not find a class matching '
--> 814                                               'the hash {}'.format(object_hash))
    815 
    816         # Restore class interface.

RestorableOpenMMObjectError: Could not find a class matching the hash -5.37556501401e+18
```
I can provide a full traceback if needed.

**Comment by dwhswenson** [comment]
Actually, this looks like it might be an `openmmtools` issue. Worst case, you may need to pin `openmmtools` to an earlier version (0.14). See if that, in combination with #768 (once it passes tests), works for you.

I wonder if @andrrizzi can shed some light on this? What's going on here is that we have an `openmmtools.integrators.VVVRIntegrator` that was saved with an earlier version of `openmmtools` (I think possibly even saved before the old `RestorableIntegrator` enabled the full interface to be rebuilt). Now we're trying to open it with the new approach. Is there some reason this hash working?

(If @andrrizzi agrees that this is an `openmmtools` issue, it might be best to move discussion over there so that other people can find it. @sroet, you might try printing the `integrator_xml`, which may give some insight into why this problem is occurring.)

**Comment by sroet** [comment]
> Worst case, you may need to pin openmmtools to an earlier version (0.14). See if that, in combination with #768 (once it passes tests), works for you.

This fixes it for me.

> you might try printing the integrator_xml, which may give some insight into why this problem is occurring.

will give this a try

current master + openmmtools 0.15:
```
<?xml version="1.0" ?>
<Integrator constraintTolerance="1e-05" kineticEnergyExpression="m*v*v/2" randomSeed="0" stepSize=".002" type="CustomIntegrator" version="1">
	<GlobalVariables _restorable__class_hash="-5375565014007251000" a=".999000499833375" b=".044699008184376096" has_kT_changed="1" kT="2.5774864660782666"/>
	<PerDofVariables>
		<sigma>
			<Value x="0" y="0" z="0"/>
			<Value x="0" y="0" z="0"/>
			<Value x="0" y="0" z="0"/>
			<Value x="0" y="0" z="0"/>
			<Value x="0" y="0" z="0"/>
			<Value x="0" y="0" z="0"/>
                        ...
        </PerDofVariables>
	<Computations>
		<Computation computationExpression="" computationType="5" computationVariable=""/>
		<Computation computationExpression="has_kT_changed = 1" computationType="6" computationVariable=""/>
		<Computation computationExpression="sqrt(kT/m)" computationType="1" computationVariable="sigma"/>
		<Computation computationExpression="0" computationType="0" computationVariable="has_kT_changed"/>
		<Computation computationExpression="" computationType="8" computationVariable=""/>
		<Computation computationExpression="(a * v) + (b * sigma * gaussian)" computationType="1" computationVariable="v"/>
		<Computation computationExpression="" computationType="4" computationVariable=""/>
		<Computation computationExpression="v + (dt / 2) * f / m" computationType="1" computationVariable="v"/>
		<Computation computationExpression="" computationType="4" computationVariable=""/>
		<Computation computationExpression="x + ((dt / 1) * v)" computationType="1" computationVariable="x"/>
		<Computation computationExpression="x" computationType="1" computationVariable="x1"/>
		<Computation computationExpression="" computationType="3" computationVariable=""/>
		<Computation computationExpression="v + ((x - x1) / (dt / 1))" computationType="1" computationVariable="v"/>
		<Computation computationExpression="" computationType="4" computationVariable=""/>
		<Computation computationExpression="v + (dt / 2) * f / m" computationType="1" computationVariable="v"/>
		<Computation computationExpression="" computationType="4" computationVariable=""/>
		<Computation computationExpression="(a * v) + (b * sigma * gaussian)" computationType="1" computationVariable="v"/>
		<Computation computationExpression="" computationType="4" computationVariable=""/>
	</Computations>
</Integrator>

**Comment by andrrizzi** [comment]
Hmm. I believe this may be caused by the fact that the `VVVRIntegrator` is not loaded in Python when `restore_interface()` is called. `RestorableOpenMMObject` builds a table `hash -> class` of all its subclasses, but if `openmmtools.integrators` is not imported at that point, then `VVVRIntegrator` is not going to be found. In `openmmtools 0.14` the restoring class was in the `integrator` module so this wasn't an issue for those integrators (although it was an issue for integrators defined outside of that module). Sorry about this.

To verify this, could you try importing `openmmtools.integrators` before restoring the engine?

**Comment by dwhswenson** [comment]
> To verify this, could you try importing openmmtools.integrators before restoring the engine?

@sroet : I have done this in #768. Can you check whether this fixes it for you (with `openmmtools=0.15`)?

(And thanks for the quick response, @andrrizzi!)

**Comment by sroet** [comment]
> To verify this, could you try importing `openmmtools.integrators` before restoring the engine?

@andrrizzi  That fixes it

**Comment by sroet** [comment]
@dwhswenson The current commit (78382fc) does not work, but adding `import openmmtools.integrators` to an IPython notebook does.

**Comment by dwhswenson** [comment]
Huh, that's weird... will look into it more, then. @sroet: in your local, can you try removing the `import openmmtools` immediately on `openmm/engine.py` line 28? Don't think that would fix, but give it a try.

**Comment by sroet** [comment]
Hmm now neither of them work anymore...

**Comment by sroet** [comment]
continuing this discussion in choderalab/openmmtools#348
