### ISSUE TITLE
snapshot modification: where is it taken into account for the acceptance?

### ISSUE THREAD

**Issue by hejung** [openpathsampling/openpathsampling#794]
I tried to find my way through the snapshot modifiers, in particular the RandomVelocities. If I am not completely mistaken in general the acceptance criterion for modified shooting snapshots should include the ratio of the stationary distributions at the snapshots. See for example the "Trajectory based rare event methods" review by Bolhuis and Dellago Equations 77 and 93/94. I am aware that the configurational part of the densities cancel when only drawing new momenta, but the kinetic part of the density will not in general. So I would expect that a \rho(x_{SP}) / \rho(x`_{SP}) is multiplied with the sample.bias somewhere. 
Where is that happening? (Or why is it not needed?)
I looked in the PathMover code and as far as I can tell all EngineMovers only take into account the bias of the selector.
Would be great if someone can clarify. (If it is indeed needed and missing I will try to fix it)

**Comment by dwhswenson** [comment]
I think, as they exist now, subclasses of `SnapshotModifier` are only for the specific cases where this isn't needed. They should work as long as:

<img width="223" alt="def_old_x_tau o" src="https://user-images.githubusercontent.com/8178546/43962643-8b0b797e-9cb8-11e8-8d65-ce53571842ef.png">

In the overall acceptance probability, the fraction on the right shows up from the ratio of the path probabilities (where path probability is $P_{AB}[x]$, Eq. 66 from that review -- note that the review uses $x$ for phase space, not configuration space).

You're absolutely right that we're missing the more general case, but the specific examples we have implemented so far are fine:

* The "direction modifiers" are isotropic, constant KE modifications. Therefore they work in either N\*E or N\*T ensembles (but have lots of restrictions in order to keep linear momentum constant). In this case, both fractions in the equation above are 1.

* `RandomVelocities` draws directly from the Boltzmann distribution -- the probability of generating the new velocities is the same as in the thermodynamic ensemble. In this case, the numerators of both fractions in the equation above are equal, as are the denominators.

You could certainly create a move where this isn't true, however. For example, you could create a modification that has a preference to align the initial velocity to some expected reaction coordinate. Then there would be an inherent bias in the generation that would have to be accounted for. (I'm not sure how useful this specific idea would be, since the trajectory itself should already be a reasonable guess for the reaction coordinate.)

Feel free to make a PR to fix this, but it may be a little tricky to maintain backwards compatibility, so pay close attention to that. Also, the roadmap for 2.0 involves a major overhaul of path movers which should fix this in general. @jhprinz and I had mountains of discussions about that years ago; in particular see #251.

**Comment by sroet** [comment]
Sorry to awaken this zombie, but I ran into a use-case for a snapshot-modifier that can generate a modifier acceptance bias (in this case I am doing a random coordinate shift before integrating, which need to take into account the acceptance due to the underlying PES).

I could implement this in two ways:
- give modifiers a way of communicating their acceptance probability (preferably together with allowing a flexible length mover to quit early if the total acceptance probability drops below a random number)
- give modifiers a way of signalling an early rejection to movers, which could be used to reject early by sampling their own probability and random number
  
which implementation would be preferred by either you? (@dwhswenson / @hejung )

**Comment by dwhswenson** [comment]
The use case makes sense. It's definitely worth making that possible. (However, I'd point to very early -- circa 1998-1999 -- TPS papers that tried a configurational MC move as shooting point modification and found it less effective than velocity modifications. If you're revisiting this for a new method, I hope the paper will contain some insight into what is different for your case!)

This gets into what should be a bit of a redesign of the shooting move, overall. I see two separate issues here:

* All stages of the shooting move should be included in the acceptance probability. 
* It should be possible, in some situations, to do an early rejection of a shooting move.

## All stages should be included in acceptance

In principle, all shooting moves should consist of the following stages:

1. Select shooting point
2. Modify shooting point (identity function on one-way shooting)
3. Propagate dynamics
4. Include an external bias on the trajectory (e.g., s-ensemble)

Currently, no OPS shooting move actually includes step 4 (although you can hack that in with a custom shooting point selector). Currently, only the shooting point selection and the dynamics are included in the acceptance probability.

It would probably be best to restructure the `EngineMover` as a base class that takes all 4 of those stages as inputs, with current movers as special case subclasses. For 1.x compatibility, I think the current shooting point selection approach might be a model. For shooting point selectors, we first use the `pick` method of the selector, and then information from that is used in a separate call to `selector.probability_ratio` to determine the contribution to the acceptance probability. For shooting point modifiers, `__call__` is the equivalent of `pick`, and there is no equivalent of `probability_ratio`. This could implemented and added to create `EngineMover` with default `modifier=None` (which must result in `NoModification()`) and a `try/except` around getting `modifier.probability_ratio` in order to keep backward compatibility (even with duck-typed custom modifiers).

For something only targeting 2.x, I'm open to a much more significant restructuring of how each stage of the process works, but please make a specific suggestion before getting too far into major (there may be other corners to consider.)

## Early rejection

First, ***early rejection for shooting movers based on total acceptance probability should not be a default behavior.*** It makes it impossible to use max-length rejection as a diagnostic for possible unknown stable states. In biological systems, that's a real concern. I'd be happy to have separate classes for early-rejection shooting movers (and the associated strategies), but I would want the canonical mover class to be different. You can even probably put the core logic in `EngineMover` and use a private class variable (perhaps wrapped with a read-only `@property`) to determine behavior.

Second, let's make a distinction between normal multistage trials and what I have previously called "bundled moves," where each stage is treated as a full MC step. Normally, people will be expecting multistage moves.

**Multistage moves.** It is not correct, in general for the modifier to be able to cause early rejection on its own in multistage moves. Early rejection can only happen in last stage of the 4 above that gives a non-trivial acceptance probability. So you can early-reject based on a partial trajectory only if the external bias (which depends on the entire trajectory) only returns 0 or 1 (we consider default "no bias" to return 1). You can only early-reject based on modifier if both the external bias and the dynamics stages can only contribute 0 or 1 to your acceptance probability.

**Bundled moves.** It is possible create a "bundled" move with early rejection. Use the OPS `ConditionalSequentialMover` for this; that's what it is designed for. The ideas are discussed in Sec. 3.1 of the OPS 2 paper, and illustrated in Fig. 5 of same. If all trial stages contribute 0 or 1 to the acceptance probability (as with the minus mover), then there's no difference between multistage and bundling (so we use this for the `MinusMover` to avoid wasting computational time on the most expensive stage).

For discussion on bundled moves vs. normal multistage propositions (including all the math) see [this gist](https://gist.github.com/dwhswenson/8340f521918f558959ac) that I wrote as a side note during the epic discussion on move structure in #251. I'd also strongly recommend reading over #251 (and probably the follow-up outline of next steps in #294) before diving too far into this -- some parts of those are outdated, but @jhprinz and I came to agreement on a number of points, much of which never got implemented. If there are any specific questions from older terminology in that issue, feel free to either post here or contact me privately.

**Comment by sroet** [comment]
> The use case makes sense. It's definitely worth making that possible. (However, I'd point to very early -- circa 1998-1999 -- TPS papers that tried a configurational MC move as shooting point modification and found it less effective than velocity modifications. If you're revisiting this for a new method, I hope the paper will contain some insight into what is different for your case!)

Nothing too fancy, just running 1D dynamics (which is analytically solvable) on a 2D PES , but I need a way to sample the second dimension. The quickest way to implement that seemed to be a MC modifier in the second dimension :laughing:  

> For discussion on bundled moves vs. normal multistage propositions (including all the math) see this gist that I wrote as a side note during the epic discussion on move structure in #251. I'd also strongly recommend reading over #251 (and probably the follow-up outline of next steps in #294) before diving too far into this -- some parts of those are outdated, but @jhprinz and I came to agreement on a number of points, much of which never got implemented. If there are any specific questions from older terminology in that issue, feel free to either post here or contact me privately.

Thanks for the pointers, will look into them
