### ISSUE TITLE
'engine' properties not stored properly 

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#804]
Hello,
I am trying to run a small simulation(TIS) using OPS. When loading back the storage, the engine properties like 'engine.options' and 'engine.name' do not show the right values. 

I am concerned with 'n_steps_per_frame'. I do not know if this is being right in the simulation. 
Following is the link to the files
[TIS_engine_issue.zip](https://github.com/openpathsampling/openpathsampling/files/2565586/TIS_engine_issue.zip)

In the `tis_running_script.py`, the values are as follows (for example)
    'n_frames_max': 6,
    'n_steps_per_frame': 3 

When I load back the engine, it shows me 
    'n_steps_per_frame': 50000, 
    'n_frames_max': 2000,

To run the script on GPU , type 
`nohup ./tis_running_script.py > log &`

I get that somehow the values are being cached from the inital_trajectory.nc. Is there a way to correct it ? Or is there a silly mistake that I am making ? Please feel free to correct 

My OPS version is : 0.9.3
Python 2

**Comment by dwhswenson** [comment]
How are you loading the engine back in? My guess is loading by number (`storage.engines[0]`)?

If that's the case, then the problem is that you have multiple engines. Every snapshot knows the engine that created it, so as soon as you save the initial trajectory, you also save the engine that created that trajectory (with options 50k steps per frame, 2k frames max). 

You can instead load by name (that's the main purpose of naming objects).

I checked out 0.9.3, ran your script (although I set number of MC steps to 0, since it will save everything before running the dynamics), and ran the following:

```python
In [1]: import openpathsampling as paths

In [2]: storage = paths.Storage("./result_storage.nc", mode='r')

In [3]: len(storage.engines)
Out[3]: 2

In [4]: storage.engines[0].options
Out[4]:
{'n_frames_max': 2000,
 'n_steps_per_frame': 50000,
 'on_error': 'fail',
 'on_max_length': 'fail',
 'on_nan': 'fail',
 'on_retry': 'full',
 'retries_when_error': 0,
 'retries_when_max_length': 0,
 'retries_when_nan': 2}

In [5]: storage.engines[0].name
Out[5]: u'TPS_280K_TIS'

In [6]: storage.engines[1].options
Out[6]:
{'n_frames_max': 6,
 'n_steps_per_frame': 3,
 'on_error': 'fail',
 'on_max_length': 'fail',
 'on_nan': 'fail',
 'on_retry': 'full',
 'retries_when_error': 0,
 'retries_when_max_length': 0,
 'retries_when_nan': 2}

In [7]: storage.engines[1].name
Out[7]: u'Random_name'

In [8]: storage.engines['Random_name'].options['n_steps_per_frame']
Out[8]: 3
```

The last line shows how to load an engine by name (and verifies that the `n_steps_per_frame` is correct).

Note that the scheme, when reloaded, is using the correct engine:

```python
In [9]: len(storage.schemes)
Out[9]: 1

In [10]: scheme = storage.schemes[0]  # only 1 exists!

In [11]: scheme.movers['shooting'][0].movers[0].engine.name
Out[11]: u'Random_name'
```

Let me know if that fixes it!

**Comment by arjunwadhawan** [comment]
Thanks @dwhswenson for the quick reply and solving it.
Yes, it fixes it (& indeed it was a silly one).

Cheers

**Comment by dwhswenson** [comment]
Glad that was all that was needed, and it's a useful issue because it points out that we should change some of the examples to use best practices for naming/reloading objects. In my opinion, the best practices are:

* Use names whenever possible: If you're likely to reload it, and if it can be given a name, then give it a name (and then reload by name).
* Special instances of objects that can't be given names (snapshots, trajectories, etc.) can be assigned a name by putting then in `tags` store, e.g., `storage.tags['name_of_snapshot'] = snapshot`, and reloaded from that.
* Reloading by number should almost never by used. Analysis will typically use an iterator, and I think everything else falls into the two cases above. I think reloading by number is mainly useful for debugging.

That said, I definitely don't always follow these best practices, even though I should. For example, since I know there's usually only one network and one scheme in my file, I almost always reload those by number. Probably a bad habit.
