### ISSUE TITLE
box vector initialization for non-periodic systems

### ISSUE THREAD

**Issue by ajsilveira** [openpathsampling/openpathsampling#832]
I am trying to simulate a system in implicit solvent.
When initializing the variables to be saved in the netCDF file, a variable
 with shape (1,3,3) is created even for non-periodic systems.
The error is:
```
File "netCDF4/_netCDF4.pyx", line 4358, in netCDF4._netCDF4.Variable.__setitem__
ValueError: cannot reshape array of size 0 into shape (1,3,3)
```

The following script reproduces the issue.
The PDB is here: https://gist.github.com/ajsilveira/3c7b9171383de68e966d958a557fb215

```
import openpathsampling
import openpathsampling.engines.openmm as omm

template = omm.snapshot_from_pdb('porin-ligand.pdb', periodic=False)
storage = openpathsampling.Storage("myfile.nc", "w")
storage.snapshots.save(template)
```

**Comment by dwhswenson** [comment]
Could you double-check the script you provide? I get that `periodic` is not a valid keyword for `snapshot_from_pdb`, which matches what I see in the code, and there are no recent changes to that function.

Are you perhaps actually using the `periodic` keyword for a `snapshot_from_testsystem`? As I recall, @jchodera has previously mocked a testsystem with a namedtuple (in code for the host-guest system, IIRC -- I'm hoping he can point you to it more easily that I can try to dig it up). That would provide a model that should create a minimal example.

I suspect that the underlying problem is an issue with how netcdfplus handles things when the box vector is `None`. @jhprinz, could you look into this? That's your code.

**Comment by ajsilveira** [comment]
Yes. You are right. I had modified the code to include that option (periodic), because I was getting this error:
```
  File "/home/silveira/miniconda3/envs/myenv/lib/python3.6/site-packages/openpathsampling-0.9.6-py3.6.egg/openpathsampling/engines/openmm/tools.py", line 108, in snapshot_from_pdb
    box_vectors=u.Quantity(pdb.unitcell_vectors[0], u.nanometers)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dwhswenson** [comment]
The `snapshot_from_pdb` code creates snapshots using a separate code base from everything else (the main code to build snapshots from MDTraj trajectories is and should be `trajectory_from_mdtraj`. I'll fix it so that it is based on that code. The entire function will probably just be to return `ops_load_trajectory(pdb_file)[0]`, so you can just use `ops_load_trajectory` instead.

However, that still gives the reshaping error. To explain that error: if a system is non-periodic, OPS sets its box vectors to `None`. Somewhere in netcdfplus, which is @jhprinz's extension to netcdf, the box vectors are still expected to be a 3x3 matrix -- actually, a list of 1 3x3 matrix, i.e., `shape (1, 3, 3)`. It looks like netcdf sees `None` as an empty numpy array, i.e., `size 0`, and tries to reshape it to the expected dimensionality.

Two variants of minimal example (one with the PDB in your gist; one with an OpenMMTools testsystem):

```python
import openpathsampling as paths
from openpathsampling.engines.openmm.tools import ops_load_trajectory
template = ops_load_trajectory('porin-ligand.pdb')[0]
storage = paths.Storage("myfile.nc", "w")
storage.save(template)
```

```python
import openpathsampling as paths
import openmmtools
testsystem = openmmtools.testsystems.AlanineDipeptideVacuum()
snap = paths.engines.openmm.snapshot_from_testsystem(testsystem, periodic=False)
storage = paths.Storage("test.nc", 'w')
storage.save(snap)
```

Both give errors ending with:

```pytb
~/Dropbox/pysrc/openpathsampling/openpathsampling/engines/features/shared.py in _save(self, configuration, idx)
    133         # Store configuration.
    134         self.vars['coordinates'][idx] = configuration.coordinates
--> 135         self.vars['box_vectors'][idx] = configuration.box_vectors
    136 
    137     def get(self, indices):

~/Dropbox/pysrc/openpathsampling/openpathsampling/netcdfplus/netcdfplus.py in __setitem__(self, key, value)
    106 
    107         def __setitem__(self, key, value):
--> 108             self.variable[key] = self.setter(value)
    109 
    110         def __getitem__(self, key):

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Variable.__setitem__()

ValueError: cannot reshape array of size 0 into shape (1,3,3)
```

I'm assigning this to @jhprinz, since this is a problem in netcdfplus and/or snapshot features, both of which were his contributions. However, he hasn't been active in development lately, so I may have to try to figure this out myself.

**Comment by ajsilveira** [comment]
I think the problem is that the variable `box_vector` is initiated in `shared.py` if a .nc file is created regardless of the system.
Would it be a good idea to remove `box_vector` from `shared.py` and include `is_periodic` as a `feature.statics`? This way 
`box_vectors` would be a netcdf variable only if `is_peridic = True`.

**Comment by dwhswenson** [comment]
@ajsilveira : What you suggest would probably work, but I'm not entirely sure whether how it would affect backward compatibility. That would require input from @jhprinz.

I'm working on a major rewrite of storage, which includes late registration of snapshots with the backend, which should solve this problem (in that case, it will only determine the dimensions of a snapshot when it is about to store the first one, so it won't try to create a 3x3 matrix from `None`). As a fix for now, I'm trying out the idea of converting `None` box vectors to all zeros (which obviously aren't valid) when they go into the storage. It increases file size a little, but only by 9 floats per snapshot. This is in #835; please try that out and let me know if it fixes the problem for you, or if any other changes are needed!

**Comment by ajsilveira** [comment]
@dwhswenson I think that worked!: I haven't analyzed the results yet, but it completed 200 MC cycles. I had to modify the engine module, as well. This is in https://github.com/dwhswenson/openpathsampling/pull/16 .
