### ISSUE TITLE
TIS pathway's rejection reason 

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#836]
Hi, this is a general question about TIS's path rejection. It can be very basic but I cant really convince myself hence posting here.

I am running a standard TIS simulation (No replica exchange etc..) using 1 way shooting across 1 interface with OPS (0.9.3). 

I have an initial path with order parameter going from State A to B (order parameter 0 to 300). Sampling interface is shown by black horizontal line (order parameter =180). I run 3 monte-carlo steps and all 3 are rejected 

![image](https://user-images.githubusercontent.com/21062948/57685171-9d8c3080-7637-11e9-9bff-51cdd869945c.png)

<img width="955" alt="Screenshot 2019-05-14 at 10 24 20" src="https://user-images.githubusercontent.com/21062948/57685266-d0cebf80-7637-11e9-8277-0060503256a9.png">

I dont really understand the reason for rejection. 

- Why is "metropolis_acceptance" = 0.0 for first 2 paths ? Is it because they are backward paths but ended up in state B (where as the backward paths should end in state A?)

- Path 3 has 'metropolis_acceptance': 0.30794330610000004. Does this means that there is 30% chance of it getting accepted and hence was rejected ? 

![image](https://user-images.githubusercontent.com/21062948/57685325-ee9c2480-7637-11e9-8d0d-75021abddee9.png)

Let me know if more information is required.
Thanks in advance

**Comment by dwhswenson** [comment]
It sounds like you pretty much figured it out. The way I would describe `metropolis_acceptance` is that it is the probability that the path will be accepted in the Metropolis algorithm. When it is 0.0, that's because the path is not valid for the ensemble (for TIS, that means B->B or doesn't cross interface), so it has zero acceptance probability. When it is nonzero, the trial is accepted if a random number between 0 and 1 is less than `metropolis_acceptance`. You can see that random number, too: it's called `metropolis_random`. (This is my go-to example when I say that OPS errs on the side of storing too much information, but the reason we do so is you can check things like this. With the results you show, it is clear that 0.7675 is not less than 0.3079).

So, to answer your specific questions:

1. Yes, the metropolis acceptance was 0.0 because the paths were B->B
2. Yes, that means a 30% (well, closer to 31%) acceptance probability, and it was rejected based on that.

Question: what shooting move are you using? That acceptance probability doesn't look right for uniform shooting, with the results you show. Are you using a different shooting point selector? (Maybe a relatively narrow Gaussian centered near your interface?)

**Comment by arjunwadhawan** [comment]
Thanks for answering David. Yes it is a Gaussian shooting selecting points closer to interface. 
I was trying to sample B ->B transition at first place. I will invert my transition and network so that B becomes A and then I can sample A -> A transition (suggested by Peter)

Cheers
