### ISSUE TITLE
Dev install script is not installing matplotlib for py35

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#846]
Hey running the following
```
conda create -n py35 python=3.5
conda activate py35
curl -OLk https://raw.githubusercontent.com/openpathsampling/openpathsampling/master/devtools/conda_ops_dev_install.sh
bash conda_ops_dev_install.sh
cd openpathsampling/
nosetests
```

results in
```
/home/blub/temp/openpathsampling/openpathsampling/numerics/histogram.py", line 4, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named 'matplotlib'
```

I expected this to be work, as the website docs still mention `python 3.5+`

edit:
After installing `matplotlib` it is still missing `openmm`, `ujson`, `NetCDF4`,  `networkx`, `openmmtools`

edit2:
As another issue, `nose` can't handle the pytest decorators 
```
TypeError: test_f() missing 1 required positional argument: 'frame'
```

while the docs still state
>  The test suite uses both pytest and, for the time being, nose.

**Comment by dwhswenson** [comment]
I don't think this is a Python 3.5-specific issue; you should be seeing the same behavior in fresh environments for other versions of Python as well.

The installation script currently requires that the `conda` package (library) be available in the environment where you run it. Typically, in non-root environments the `conda` *executable* is available, but you'll get an error if you try `python -c "import conda"`. I'll make a PR to remove that requirement. Originally the `install_recipe_requirements.py` script was supposed to handle the installation; now it is just used for getting a list of requirements out of the recipe (so `conda.cli` is no longer required).

The recommended way to accomplish what you're doing would be (from the root environment, or one where you've done `conda install conda`)

```bash
OPS_ENV=py35 CONDA_PY="3.5" source conda_ops_dev_install.sh
```

That will create the environment, use Python 3.5, and leave the new environment active (by using `source` instead of forking a separate process with `bash`). You could also install conda into your `py35` environment before running the dev install script, but in my experience, leaving conda installed in non-root environments can cause problems in the long term (conflicting conda versions can make a mess).

BTW, while OPS should run on Python 3.5, it's no longer officially supported (i.e., we don't test against 3.5). Building for 3.5 in tests became more difficult as conda-forge stopped building for 3.5 (and there was some weird issue with some packages seeming to disappear). That's something I should update in the docs.

> while the docs still state
>> The test suite uses both pytest and, for the time being, nose.

This should be clarified. What we mean is that `nose` is required as a library (legacy from switching test suites, old tests still use `assert`s, etc. from `nose`). However, the executable from `pytest` should be used.
