### ISSUE TITLE
Out of bounds on buffer access (axis 0), on branch gromacs_engine

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#855]
In the AD_tps_2a_run_flex notebook, running a sampler with 1000 Monte Carlo cycles eventually gave the attached error.
[error.txt](https://github.com/openpathsampling/openpathsampling/files/3636436/error.txt)

**Comment by arjunwadhawan** [comment]
For reference , we are trying to run TPS on Alanine dipeptide using the gromacs notebook. 
We have installed the latest version of both gromacs and OPS

**Comment by dwhswenson** [comment]
I'm working on this, but it might take a little while. Unfortunately, I'm travelling for a few days (literally in the train as I type) and so I may not be able to do much on this until Thursday, when I'm back at the ENS.

I think the problem relates to the fact that we try to read files while they are being written. The AD example is a particularly rough case for this: only 1653 atoms, and we write to disk every 10 time steps. With a more realistic research system, writing to disk would be a much smaller fraction of the total computing time, so you'd be less likely to poll the file system when the file was in the middle of being written.

When I tried to reproduce your error, I actually had a different error (related to max number of files open), which I've fixed. It turns out that when MDTraj had an error while opening a file that was being written, it left the file open. If the OS only allowed a small number of files open at once (for some reason, mine is 256), then it would crash once that number of files was open.

With that fixed, I have been able to reproduce the error you found. In my runs, this error seems to happen on the first frame of a trajectory. I have no idea why that would be. I have a rough idea for a generic workaround that might protect against the general problem of getting this error during a trajectory, but I don't have any explanation for why it is always the first frame.

**Comment by dwhswenson** [comment]
Turns out, I could charge my laptop at my train seat. So I could run Gromacs without completely draining my laptop battery.

Possible fix added to the `gromacs_engine` branch. Please try it out. I also updated the example notebook to reflect better usage (better ways of loading old objects, plus defaulting to less logging and explaining how to put debug-level logging in a file). You'll want [revert the changes you've made](https://docs.gitlab.com/ee/topics/git/numerous_undo_possibilities_in_git/#unstaged-local-changes-before-you-commit) by running your local copy of the notebook, otherwise there will be a conflict when you try to merge in the update.

I ran for 200 steps, and the workaround for this was called 5 times, according to the logs. Three times it was the very first snapshot that gave the problem; once it was the second snapshot, and once is was the fourth. It always happens early in the trajectory. I don't know why.

**Comment by IdsTeepe** [comment]
This fix does indeed work. However, the step shows as None during analysis. Not that this is harmful, yet..

**Comment by dwhswenson** [comment]
> However, the step shows as None during analysis.

I'm not sure what you mean by this. In my own check (200 MC steps; usually means a few examples of this problem) I did not see anything where either the MC step was reported as `None` or where the MD snapshot was reported as `None`. If either of those are happening, it *would* be a significant concern!

**Comment by IdsTeepe** [comment]
I'm sorry, I was mistaken. The snapshots are not returned as None.
