### ISSUE TITLE
Error on branch gromacs_engine when submitting job to workload manager

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#857]
Recently, I've been trying to get the gromacs_engine branch to work on a computer cluster. Recently I've got it all running when invoking a command from the command line. When submitting an ops-script to the workload manager (SLURM) however, many errors arise. 
I've tried multiple things, such as setting a specific amount of threads using `-nt` or `-ntmpi` from 1-24,  and switching between invoking `gmx` and `gmx_mpi`. As of yet, none of them were successful however.
Attached is an error log of the simple alanine dipeptide example run, with `'mdrun_args': " -ntmpi 8"` using `gmx -quiet`. This starts off with a few errors:
> FileNotFoundError: [Errno 2] No such file or directory: './initial_frame.trr'

Though they don't seem to do kill the job.
Later on, though, there are errors regarding reading a trr file:

>   File "mdtraj/formats/xtc/trr.pyx", line 722, in mdtraj.formats.trr.TRRTrajectoryFile.seek
> OSError: TRR Seek out of bounds: given absolute position: 3

> File "mdtraj/formats/xtc/trr.pyx", line 273, in mdtraj.formats.trr.TRRTrajectoryFile._check_has_velocities_forces
> RuntimeError: could not read header of first frame!

Eventually, the job gets terminated because of child processes exiting with an error code:

> srun: error: tcn567: tasks 5,11,13-14,17-18,21-23: Exited with exit code 1
> srun: Terminating job step 6875108.0
> srun: Job step aborted: Waiting up to 32 seconds for job step to finish.

Please also take a look at the following log:
[error_multithread.txt](https://github.com/openpathsampling/openpathsampling/files/3653873/error_multithread.txt)

If you find it too messy, I've also uploaded a cleaned-out version:
[error_multithread_small.txt](https://github.com/openpathsampling/openpathsampling/files/3654111/error_multithread_small.txt)

**Comment by dwhswenson** [comment]
Could you share the SLURM script you're using? (Feel free to remove things like account IDs from the header; the main thing it that I need to see the shell script you ran.)

I want to see if there's something obviously problematic in that; if not, then I'll see if some colleagues with more expertise in HPC/parallelization can help.

**Comment by IdsTeepe** [comment]
Of course! Besides some arguments being passed, the SLURM script is just one line really.
I call the following script using `sbatch script_batch.sh`:
```
#!/bin/bash
# J name, p partition (type of node), n amount of cores, t max compute time, D working dir
# Setting the amount of cores for the entire batch equal to the amount of cores for a single run, 
# one specifies to just run once.

# NOT SPECIFYING TIME MEANS A RUNTIME OF 5 MINUTES!
# time is specified in [HH:]₂MM[:SS]₁ or in D-HH[:MM[:SS]]
# Maximum runtime is 5-00.

# NONE OF THE ARGUMENTS BELOW ARE PASSED IF ANY ARGUMENT IS PASSED IN THE COMMAND LINE

#SBATCH -J OPS
#SBATCH -p short
#SBATCH -n 24
#SBATCH -D .
#SBATCH -t 0-01
srun -n 24 ~/script_python.sh "$1"
```
`~/script_python.sh` looks like this:
```
#!/bin/bash
python3 "$1"
```

**Comment by dwhswenson** [comment]
I don't think you want to use the `-n 24` argument to `srun`. In fact, I'm not sure that you even need to use `srun` at all. The `-n 24` argument tells `srun` to run 24 copies of the script; i.e., 24 copies of OPS. This means that 24 copies are fighting over the same filenames, so that would definitely cause some of those errors. I'm pretty sure you what you want is 1 copy of OPS with 24 cores reserved (so you can launch Gromacs and have it use those cores).

From https://stackoverflow.com/a/43799481:

> If your program is a parallel MPI program, `srun` takes care of creating all the MPI processes. If not, `srun` will run your program as many times as specified by the `--ntasks` option.

In your script, you want the `#SBATCH` commands to set up the environment, and then the `gmx` command to determine how you'll use it. I think that it `gmx` will automatically use OpenMP to fill the whole node, if you're running 1 trajectory per node. Otherwise, you need to tell it about the size of your allocation.

---

Additional note: for debug purposes, it will be useful to know the current working directory. I'd recommend adding a line to your Python script like:

```python
print("Working directory: " + os.path.realpath(os.getcwd()))
```

That prints the absolute path (realpath) of the current working directory (getcwd). Obviously, you need to `import os` at some point earlier, if you haven't already.

**Comment by IdsTeepe** [comment]
> I don't think you want to use the `-n 24` argument to `srun`.

Wow, setting the argument to `-n 1` did indeed resolve all my issues; I feel like an idiot.
I guess the fact that `-n` is used by `sbatch` to set the amount of cores made me expect it did the same for `srun`, hence me setting the same value for both. I'm sorry for not figuring this out by myself.
