### ISSUE TITLE
Accessing an old storage made by unknown OPS version

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#869]
Hi,
I had generated some data using OPS(version > 0.9.4) which seemed pretty redundant at that time. So I did not care to keep track of the OPS version (and other dependencies). Now I want to use that storage to extract some frames. 

Sadly the new OPS version cant load the storage properly. In the sense that like "Move details" cant be read in. What could be a work around this ? 

I am not even sure if these details were stored in properly. 

![image](https://user-images.githubusercontent.com/21062948/67468182-5a080a80-f64a-11e9-8f99-c8473a10f39a.png)
 
![image](https://user-images.githubusercontent.com/21062948/67468246-7441e880-f64a-11e9-9daa-7fad08114660.png)

**Comment by dwhswenson** [comment]
This looks to me like something else is going wrong in the analysis script. In the first error, for some reason it seems to think that `steps[1].change` is a `MoveDetails` object. It should be some variant of a `MoveChange`. The second error suggests that there was a problem loading the move scheme: apparently it returned `None` instead of giving you a move scheme.

We test the analysis example notebooks against files created with OPS 0.9.1 for Python 2.7, and 0.9.3 for Python 3.6/3.7. It's just a smoke-test, but that means that it shouldn't raise an error. Note that you do need to use the same version of Python as the file was created with, although that would raise an error about reloading the CVs (opcodes changed in Python 3, and again in Python 3.6).

You can get more information about the nc file from the shell (e.g., bash) with the command `ncdump -h $filename`. In particular, near the end you should see something that looks like:

```
// global attributes:
		:format = "netcdf+" ;
		:ncplus_version = "0.9.3" ;
		:storage_format = "openpathsampling" ;
		:storage_version = "0.9.3.dev-315f6f9" ;
		:use_uuid = "True" ;
```

This should tell you the versions of OPS and netcdfplus used generate the file. Trust the `ncplus_version` over the `storage_version` (if you have a developer install, at least).

I'd suggest going over your script carefully, and checking the `type` when something raises an error. For example, in the first error, what is `type(steps)`? `type(steps[1])`? `type(steps[1].change)`? At some point, this is giving the wrong thing. For the second one, how exactly do you load `flex_scheme`? Does the storage actually have a move scheme in it? (`len(storage.schemes)`)

Storage hasn't changed much since OPS 0.9.3 was released (adding Python 3 support), so I don't think it is due us introducing breaking changes.

**Comment by arjunwadhawan** [comment]
Hi David,
I use the same python version(python 2). And `ncdump -h` gives the following 

```
// global attributes:
		:format = "netcdf+" ;
		:ncplus_version = "0.9.3" ;
		:storage_format = "openpathsampling" ;
		:storage_version = "0.9.3.dev-f82c987" ;
		:use_uuid = "True" ;
```

I activated the same conda env and tried the following 
![image](https://user-images.githubusercontent.com/21062948/67751595-adef6680-fa31-11e9-98b3-d099f71430c3.png)

Second Error 
![image](https://user-images.githubusercontent.com/21062948/67751614-b8a9fb80-fa31-11e9-8cbd-e50a6a1ac439.png)

I am a bit confused why there is no scheme. For reference I have attached my TPS setup script 
[tps_setup.py.zip](https://github.com/openpathsampling/openpathsampling/files/3782506/tps_setup.py.zip)

**Comment by dwhswenson** [comment]
For the first error, try the following:

```python
import openpathsampling as paths
assert 'canonical' in dir(paths.PathSimulatorMoveChange)
assert paths.MoveChange.canonical is paths.PathSimulatorMoveChange.canonical
```

Passes for me in the current master. Are you in a developer install?

For the second error, I'm not sure if this will work, but try:

```python
for sch in spring_storage.schemes:
    print "Scheme=", sch
    scheme = sch
```

I'm curious (1) how many it will print; (2) if `scheme` is defined after that (if it prints 0 times, `scheme` will not be defined.)

**Comment by arjunwadhawan** [comment]
Hi,  first passes, second is "None"

![image](https://user-images.githubusercontent.com/21062948/67841347-29b3e680-faf8-11e9-90e7-1d1c93df5f2b.png)

**Comment by IdsTeepe** [comment]
I have the same issue. Everything runs (and stores) fine with a `openpathsampling.OneWayShootingMoveScheme`, but when using a `spring_shooting.SpringShootingMoveScheme`.. Take this example from the alanine dipeptide notebook. All I did was change the move scheme:
Initially, everything works fine. Trees show correctly, and move summaries can be printed. I can even delete all variables, reload the storage, and everything is still OK:
![image](https://user-images.githubusercontent.com/29386374/67941205-74eff700-fbd5-11e9-833d-fe8693f8533d.png)
Getting the direction also works fine:
![image](https://user-images.githubusercontent.com/29386374/67941544-20994700-fbd6-11e9-877e-106ceb9f070b.png)

As soon as I try to load the storage in a different notebook / script, however, the tree doesn't show properly (as the MoveScheme is 'None' probably) and I get the same errors as Arjun:
![image](https://user-images.githubusercontent.com/29386374/67941308-a668c280-fbd5-11e9-9e6b-c7206b68b98c.png)
and:
![image](https://user-images.githubusercontent.com/29386374/67941735-98677180-fbd6-11e9-8467-d198d1bbe023.png)
![image](https://user-images.githubusercontent.com/29386374/67941904-e3818480-fbd6-11e9-9651-55d9238b1afc.png)


I had been wondering for weeks how I got green trees when using spring shooting.

**Comment by dwhswenson** [comment]
This sounds to me like it's a problem with the code for spring shooting, which isn't in the core of OPS yet. Exactly where are you getting that code from? (either from Sander's PR #850, or the repo where he developed it: https://gitlab.e-cam2020.eu/sroet/spring_shooting) In either case, please also identify the specific commit you're using and make sure you're using the most up-to-date version. (I thought he had included storage tests; I remember thinking that was a good idea and something I should also do more of.)

This may be something that Sander will have to deal with, but I don't think he has bandwidth for it now (which is why I haven't been @-mentioning him here.)

**Comment by dwhswenson** [comment]
(For context: OPS does a lot of caching of objects, so unless you actually start a new Python kernel, the cached stuff may still be around. That's why it works when you do it in the same notebook. All of that was @jhprinz's magic, so I don't know exactly how it goes.)

**Comment by dwhswenson** [comment]
Wait... when you're starting up the new notebook for analysis, do you import spring shooting? You need to do that, otherwise OPS has no idea what to do with the spring shooting objects. The storage stores a description of the object, but it doesn't store the code itself. You need to provide the context so that description can deserialize the object.

**Comment by IdsTeepe** [comment]
> Exactly where are you getting that code from?

I got it from here: https://gitlab.e-cam2020.eu/sroet/spring_shooting/tree/master
I think Arjun too..

> For context: OPS does a lot of caching of objects, so unless you actually start a new Python kernel, the cached stuff may still be around.

Yes I noticed. When trying things in the same notebook, `from_storage.steps[1].change.canonical` works fine. However, `MoveChange.__getattr__` also doesn't get called.
While still having everything loaded, I can do:
```
print(from_storage.steps[1].change.subchanges[0].mover)
print(from_storage.steps[1].change.subchanges[0].subchanges[0].mover)
print(from_storage.steps[1].change.subchanges[0].subchanges[0].subchanges[0].mover)
print(from_storage.steps[1].change.subchanges[0].subchanges[0].subchanges[0].subchanges[0].mover)
-------------------------------------
RootMover
ShootingChooser
SpringShootingMover [SequentialEnsemble]
BackwardSpring
```

When trying the same after loading the storage in another kernel:
```
RootMover
ShootingChooser
None
None
```
So somehow, the spring shooting part doesn't get stored.

**Comment by IdsTeepe** [comment]
> Wait... when you're starting up the new notebook for analysis, do you import spring shooting?

Well that does solve the issue from my side! @arjunwadhawan is this also the case for you?

> The storage stores a description of the object, but it doesn't store the code itself. You need to provide the context so that description can deserialize the object.

When you bring it like this, it seems very logical in hindsight. It seems I thoroughly need to change the way I think about storages. I'm sorry and thank you!

**Comment by arjunwadhawan** [comment]
Importing spring shooting does solves this issue 
Thanks @dwhswenson for pointing this out. It completely makes sense and was a rookie's mistake.
Thanks @IdsTeepe for checking
