### ISSUE TITLE
Run continues, but no output or storage written.

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#870]
I have a run (with gromacs engine) that's still continuing, still generating files, still killing `gmx mdrun` and starting new steps, etc. 
I can still read the process output and see that the run creating trajectory 55 now. However, `ops_output.log` and the storage are not being written to since step 5.
The process output gives the following at step 5:
```
Working on Monte Carlo cycle number 5
Running for 50 minutes 25 seconds - 756.38 seconds per step
Estimated time remaining: 8 days 17.26 hours
Index:161, Prev. shooting index:163
Traceback (most recent call last):
  File "111.py", line 100, in <module>
    sampler.run(1000)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathsimulators/path_sampling.py", line 228,
 in run
    movepath = self._mover.move(self.sample_set, step=self.step)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 2559, in move
    self.mover.move(sample_set),
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 1582, in move
    subchange = mover.move(sample_set)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 1582, in move
    subchange = mover.move(sample_set)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 1582, in move
    subchange = mover.move(sample_set)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 613, in move
    change = self.move_core(samples)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 640, in move_core
    trials, call_details = self(*samples)
  File "/home/10433791/ops/spring_shooting-master/spring_shooting/spring_shooting.py", line 295, in __ca
ll__
    shooting_index)
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 900, in _run
    trajectory, shooting_index
  File "/home/10433791/ops/openpathsampling/openpathsampling/pathmover.py", line 860, in _make_forward_t
rajectory
    running=[run_f])
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/dynamics_engine.py", line 423, in g
enerate
    for trajectory in it:
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/dynamics_engine.py", line 517, in i
ter_generate
    self.start()
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/external_engine.py", line 141, in s
tart
    self.write_frame_to_file(self.input_file, self.current_snapshot, "w")
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/gromacs/engine.py", line 332, in wr
ite_frame_to_file
    + "Preventing overwrite.")
RuntimeError: File ./initial_frame.trr exists. Preventing overwrite.
Error in sys.excepthook:

Original exception was:
```
Strangely enough, the process didn't crash and is still running. My most pressing question is: Can I still recover the data? That is, can I distill the last accepted trajectory? Otherwise I'll just kill it and deem it a one-time exceptional error.

**Comment by dwhswenson** [comment]
In short, I would kill it. But I'm trying to think how on earth it is even possible.

The error happened because of a race condition that I didn't think was possible in Python (because the [GIL](https://realpython.com/python-gil/)). The `GromacsEngine` is designed to prevent you from overwriting existing files, and errors if you try to (that's the error you see). In this case, you're trying to overwrite the initial frame -- the engine is supposed to delete that file at the end of a trajectory. Apparently it didn't delete it fast enough. I thought the GIL would prevent that from happening. Guess not. I have an idea of how to fix it (basically, after telling the OS to delete the file, wait around until the file is actually deleted), and will do that sometime soon.

What's really weird is that you're still creating new trajectories. Continuing the same one makes sense, but that error should have brought everything in the OPS process to a stop. I have absolutely no idea how that's possible. And if storage isn't changing, you're losing information about whether they were accepted or rejected.

You're not running more than one Gromacs engine in the same directory at the same time, are you? That's the only way I could imagine this happening -- if you accidentally had a *different* process generating that data, and this one had really crashed. (Although I thought that would have created an error anyway.)

**Comment by IdsTeepe** [comment]
> What's really weird is that you're still creating new trajectories. Continuing the same one makes sense, but that error should have brought everything in the OPS process to a stop.

That's also what I thought. I am certain that the steps are still accepted and rejected, but the only way of figuring out whether they were accepted / rejected is loading the trajectories with mdtraj, checking the CV's and determining manually whether they reached the correct state. That's going to be too much work.

> You're not running more than one Gromacs engine in the same directory at the same time, are you?

I certainly don't, this was the only gromacs engine OPS process on the cluster.
That being said.. This run does make use of GPU. OPS itself is running on CPU but delegates the hard work to GPU by calling `gmx mdrun -gpu_id 0`. Could this cause any unexpected behaviour?

**Comment by dwhswenson** [comment]
I don't see any way that running using Gromacs with GPU should have caused this. I mean, it might make affect timing of killing a Gromacs process, making errors like this more likely, but no matter what I don't see how the Python process survived a fatal error.

**Comment by IdsTeepe** [comment]
Another possible explanation is that I used `nohup` to call the script and let it run in the background unhindered. I don't know what kind of signal gets sent to kill python after that fatal error, but it might've gone unnoticed because of `nohup`.

**Comment by dwhswenson** [comment]
I still see no reason that this would occur -- has this happened again, or was it just a freak occurrence?

**Comment by IdsTeepe** [comment]
I'm sorry for the radio silence. It seems to have just been a freak occurrence.
